class CustomException(Exception): ...


class GoogleException(CustomException): ...


class DiscordException(CustomException): ...


class FacebookException(CustomException): ...


class TelegramException(CustomException): ...


class GithubException(CustomException): ...


class ClientNotFound(GoogleException): ...


class ClientSecretNotFound(GoogleException): ...
